acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.ulogin, name="login"),
    path('logout/', views.ulogout, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('signup/', views.signup, name="signup"),
    path('update/', views.update, name="update"),
    path('chpass/', views.chpass, name="chpass")
]

board/urls.py
from django.urls import path
from . import views

app_name = "board"

urlpatterns = [
    path('index/' , views.index, name="index"),
    path('detail/<bpk>', views.detail, name="detail"),
    path('delete/<bpk>', views.delete, name="delete"),
    path('create/', views.create, name="create"),
    path('update/<bpk>', views.update, name="update"),
    path('likey/<bpk>', views.likey, name="likey"),
    path('unlikey/<bpk>', views.unlikey, name="unlikey")
]

book/urls.py
from django.urls import path
from . import views

app_name = "book"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('create/', views.create, name="create")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('acc.urls')),
    path('board/', include('board.urls')),
    path('trans/', include('trans.urls')),
    path('tts/', include('tts.urls')),
    path('vote/', include('vote.urls')),
    path('book/', include('book.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from acc.models import User
from django.utils import timezone

# Create your models here.f
class Board(models.Model):
    subject = models.CharField(max_length=100)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="writer")
    content = models.TextField()
    pubdate = models.DateTimeField(default=timezone.now)
    likey = models.ManyToManyField(User, blank=True, related_name="likey")

    def __str__(self):
        return self.subject

    def ishot(self):
        if self.likey.count() > 2:
            return True
        return False


class Reply(models.Model):
    b = models.ForeignKey(Board, on_delete=models.CASCADE)
    replyer = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()

    def __str__(self):
        return f"{self.b}_{self.replyer} 의 댓글"

board/views.py
from django.shortcuts import render, redirect
from .models import Board
from django.core.paginator import Paginator
# Create your views here.
def likey(request, bpk):
    b = Board.objects.get(id=bpk)
    b.likey.add(request.user)
    return redirect("board:detail", bpk)

def unlikey(request, bpk):
    b = Board.objects.get(id=bpk)
    b.likey.remove(request.user)
    return redirect("board:detail", bpk)


def index(request):
    pg = request.GET.get("page", 1)
    kw = request.GET.get("kw", "")
    cate = request.GET.get("cate", "")

    if kw:
        if cate == "sub":
            b = Board.objects.filter(subject__startswith=kw)
        elif cate == "wri":
            try:
                from acc.models import User
                u = User.objects.get(username=kw)
                b = Board.objects.filter(writer=u)
            except:
                b = Board.objects.none()
        elif cate == "con":
            b = Board.objects.filter(content__contains=kw)
    else:
        b = Board.objects.all()

    pag = Paginator(b, 10)
    obj = pag.get_page(pg)
    context = {
        "bset" : obj,
        "kw" : kw,
        "cate" : cate
    }
    return render(request, "board/index.html", context)

def update(request, bpk):
    b = Board.objects.get(id=bpk)

    if b.writer != request.user:
        # 메세지
        return redirect("board:index")

    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        b.subject, b.content = s,c
        b.save()
        return redirect("board:detail", bpk)
    context = {
        "b" : b
    }
    return render(request, "board/update.html", context)

def create(request):

    if request.user.is_anonymous:
        return redirect("board:index")
    
    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        Board(subject=s, writer=request.user, content=c).save()
        return redirect("board:index")
    return render(request, "board/create.html")

def delete(request, bpk):
    b = Board.objects.get(id=bpk)
    if request.user == b.writer:
        b.delete()
    else:
        pass # 메세지
    return redirect("board:index")

def detail(request, bpk):
    
    if request.user.is_anonymous:
        return redirect("board:index")
    
    b = Board.objects.get(id=bpk)
    context = {
        "b" : b
    }
    return render(request, "board/detail.html", context)

templates/board/create.html
{% extends 'base.html' %}
{% block con %}

    <h1><b>게시글 작성</b></h1>

    <form method="post">
        {% csrf_token %}
        <div class="mb-3 mt-5">
            <label class="form-label"><b>SUBJECT</b></label>
            <input type="text" name="sub" class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label"><b>WRITER</b></label>
            <input type="text" class="form-control" value="{{ user }}" disabled>
        </div>
        <div class="mb-3">
            <label class="form-label"><b>CONTENT</b></label>
            <textarea class="form-control" name="con" style="height: 150px;"></textarea>
        </div>
        <div class="text-end mt-3">
            <button class="btn btn-dark">생성</button>
        </div>
    </form>
{% endblock %}

templates/board/detail.html
{% extends 'base.html' %}
{% block con %}

    <h1><b>{{ b.subject }}</b></h1>

    <div class="text-end">
        <button type="button" class="btn btn-outline-warning" data-bs-toggle="modal" data-bs-target="#star">
            ✨
        </button>
    </div>

    <div class="row mt-4">
        <div class="col-sm-9">
            <textarea class="form-control" style="height:200px" disabled>{{ b.content }}</textarea>
        </div>
        <div class="col-sm-3">
            <img src="{{ b.writer.getpic }}" width="100%">
            <div class="text-center mt-3">
                <h5>written by <b>{{ b.writer }}</b></h5>
            </div>
            <div class="text-end mt-3">
                <b>{{ b.pubdate | date:'Y년 m월 d일 / H:i' }}</b>
            </div>
        </div>
    </div>

    <div class="text-end mt-4">
        <a href="{% url 'board:index' %}" class="btn btn-dark">글목록</a>

        {% if user in b.likey.all %}
            <a href="{% url 'board:unlikey' b.id %}" class="btn btn-danger">👍🏻</a>
        {% else %}
            <a href="{% url 'board:likey' b.id %}" class="btn btn-primary">👍🏻</a>
        {% endif %}

        {% if user == b.writer %}
            <a href="{% url 'board:update' b.id %}" class="btn btn-dark">글수정</a>
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#remove">
                글삭제
            </button>
        {% endif %}

    </div>


    <!-- Modal -->
    {% if user == b.writer %}
        <div class="modal fade" id="remove" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel"><b>게시글 삭제 알림창</b></h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        정말 삭제하시겠습니까?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
                        <a href="{% url 'board:delete' b.id %}" class="btn btn-danger">삭제</a>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}


    <form method="post" action="{% url 'book:create' %}">
        {% csrf_token %}
        <div class="modal fade" id="star" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">즐겨찾기 추가 알림창</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">

                        <div class="text-end">
                            <input type="checkbox" name="impo" class="btn-check" id="btn-check-outlined" autocomplete="off">
                            <label class="btn btn-outline-warning" for="btn-check-outlined">✨</label><br>
                        </div>
                        <input type="hidden" name="sname" value="[BOARD]::{{ b.subject }}">
                        <input type="hidden" name="surl" value="{{ request.path }}">
                        <textarea class="form-control mt-3" name="scon" placeholder="사이트를 간략하게 설명해주세요" style="height: 100px;"></textarea>
                        
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                        <button class="btn btn-primary">북마크추가</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

templates/board/index.html
{% extends 'base.html' %}
{% block con %}
    {% load mathfilters %}

    <h1><b>게시판</b></h1>
        
    <div class="text-end">
        <a href="{% url 'board:create' %}" class="btn btn-dark">게시글생성</a>
    </div>

    <table class="table table-hover mt-4">
        <thead>
            <tr class="table-dark">
                <th scope="col">NO</th>
                <th scope="col">SUBJECT</th>
                <th scope="col">SUMMARY</th>
                <th scope="col">WRITER</th>
                <th scope="col">LIKEY</th>
            </tr>
        </thead>
        <tbody>
            {% for i in bset %}
                <tr {% if i.ishot %} style="background-color: rgba(255, 0, 0, 0.151);" {% endif %}>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td><a class="sub" href="{% url 'board:detail' i.id %}">{{ i.subject }}</a></td>
                    <td>{{ i.content | truncatewords:10 }}</td>
                    <td>{{ i.writer }}</td>
                    <td>{{ i.likey.count }}</td>
                </tr>
            {% empty %}
                <tr>
                    {% if kw %}
                        <th colspan="5">검색결과가 없습니다 😅</th>
                    {% else %}
                        <th colspan="5">첫 번째 게시글을 작성해주세요 😂</th>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <nav aria-label="Page navigation example" class="mt-4">
        <ul class="pagination justify-content-center">

            {% if bset.has_previous %}
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page=1">처음</a></li>
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{ bset.previous_page_number }}">이전</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link">처음</a></li>
                <li class="page-item disabled"><a class="page-link">이전</a></li>
            {% endif %}
        

            {% for i in bset.paginator.page_range %}
                {% if bset.number|add:3 >= i and i >= bset.number|sub:3 %}
                    <li class="page-item {% if bset.number == i %} active {% endif %}"><a class="page-link" href="{% url 'board:index' %}?page={{i}}">{{i}}</a></li>
                {% endif %}
            {% endfor %}

            {% if bset.has_next %}
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{ bset.next_page_number }}">다음</a></li>
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{ bset.paginator.num_pages }}">마지막</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link">다음</a></li>
                <li class="page-item disabled"><a class="page-link">마지막</a></li>
            {% endif %}
        
        </ul>
    </nav>

    <form>
        <div class="row">
            <div class="col-sm-2">
                <select class="form-select" name="cate">
                    <option value="sub" {% if cate == "sub" %} selected {% endif %}>제목</option>
                    <option value="wri" {% if cate == "wri" %} selected {% endif %}>작성자</option>
                    <option value="con" {% if cate == "con" %} selected {% endif %}>내용</option>
                </select>
            </div>
            <div class="col-sm-6">
                <input type="text" name="kw" value="{{kw}}" class="form-control">
            </div>
            <div class="col-sm-2">
                <button style="width:100%" class="btn btn-dark">검색</button>
            </div>
            <div class="col-sm-2">
                <a style="width:100%" class="btn btn-secondary" href="{% url 'board:index' %}">초기화</a>
            </div>
        </div>
    </form>

    <style>
        .sub {
            text-decoration: none;
            color:black;
            font-weight: bold;
        }
        .sub:hover{
            color:red;
        }
    </style>



{% endblock %}

templates/board/update.html
{% extends 'base.html' %}
{% block con %}


    <!-- board/update.html -->

    <h1><b>게시글수정</b></h1>

    <form method="post">
        {% csrf_token %}
        <div class="mb-3 mt-5">
            <label class="form-label"><b>SUBJECT</b></label>
            <input type="text" name="sub" value="{{b.subject}}" class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label"><b>WRITER</b></label>
            <input type="text" class="form-control" disabled value="{{ b.writer }}">
        </div>
        <div class="mb-3">
            <label class="form-label"><b>CONTENT</b></label>
            <textarea class="form-control" name="con" style="height: 150px;">{{ b.content }}</textarea>
        </div>
        <div class="text-end mt-3">
            <button class="btn btn-dark">수정</button>
        </div> 
    </form>

{% endblock %}